### ISSUE TITLE
Bind-mounting read-only grafana.ini causes: chown: changing ownership of '/etc/grafana/grafana.ini': Read-only file system

### ISSUE THREAD

**Issue by wpalmer** [grafana/grafana-docker#51] opened 2016-09-10 16:06 UTC
run.sh fails when the ownership of grafana.ini cannot be changed, which means that /etc/grafana/grafana.ini cannot be bind-mounted as read-only.

Specifically, it exits with the error:
`chown: changing ownership of '/etc/grafana/grafana.ini': Read-only file system`

**Comment by johanot** [comment] 2017-05-23 12:48
Bump. Ended up copying grafana.ini into my container image instead of voluming it. Mounting it as RW is not an acceptable option.

**Comment by sandersaares** [comment] 2017-08-22 07:55
This remains an issue.

**Comment by microbug** [comment] 2017-11-06 10:52
Indeed it does.

**Comment by AleksanderGrzybowski** [comment] 2017-12-10 14:06
Any update on this? I'm trying to use this with `docker config` feature and the same problem appears.

**Comment by ahrtr** [comment] 2017-12-25 02:13
Any update on this?

**Comment by danh-fissara** [comment] 2018-01-10 15:38
This is happening because the entrypoint script tries to chmod `/etc/grafana`, which happens to overlap with where the config file is by default.
https://github.com/grafana/grafana-docker/blob/b96242c3f767470465d981b3bf3d6e23baee5b00/run.sh#L10

Looking at what actually gets created there, there's only an ldap config file:
```
# ls -l
-rw-r-----.  1 grafana grafana 13099 Nov 16 09:48 grafana.ini
-rw-r-----.  1 grafana grafana  3469 Nov 16 09:48 ldap.toml
```

Question to devs: Is this ownership necessary? AFAIK config under /etc is normally owned by root.

As a workaround, you can mount `grafana.ini` elsewhere, and use the `GF_PATHS_CONFIG` env var to override the default. E.g.

    docker run -v /root/grafana.ini:/grafana.ini:ro -e GF_PATHS_CONFIG=/grafana.ini grafana/grafana

**Comment by microbug** [comment] 2018-01-10 19:38
Working on the assumption that `/etc/grafana` doesn't need to be read-write, I added read-only support to my Grafana container, which also sorts out the problems with UID/GID differing between host and container. My container builds on `grafana/grafana:latest` so it should always be up to date.

In testing it seems to work fine with a read-only `/etc/grafana` mounted. As far as I can tell the only things that get placed in `/etc/grafana` are `grafana.ini` and `ldap.toml`, neither of which should ever be edited by the container, so read-only mounting shouldn't be a problem.

https://github.com/microbug/grafana

**Comment by xlson** [comment] 2018-03-13 13:59
Fixed in 291c81788c0a823ce228c50d14713691a64390e2

**Closed by xlson** 2018-03-13 13:59 UTC

**Comment by sandersaares** [comment] 2018-03-13 14:20
I am not so sure about that. Is this really a fix?

Consider:

* I mount /home/whatever/ on the host to /etc/grafana/ in the container.
* I chown the directory and contents as root:root on the host and chmod to user-only access (so only root can view it and the secret credentials within).
* I start the container.

What happens? Startup script does nothing (no chown anymore) but when Grafana itself starts as the container-nonroot-user it cannot access the configuration file because it is chmod so that only root can access it.

The problem is not the chmod, it is that Grafana does not run as root inside the container, IMO.

**Comment by xlson** [comment] 2018-03-14 09:41
Hi @sandersaares,

There are several problems with how we handle file ownership and what user grafana runs as inside the container that, those issues are being tracked in #141. The issue being dealt with in this issue (#51) is the chowing of `/etc/grafana` and the problems it causes, as we no longer do that it is resolved.

When it comes to chowing it is something I wish to remove completely, if you volume mount a file system into the container it is your responsibility as a user to make sure that the files and folders within that filesystem has the correct file permissions for Grafana to be able to use them. Currently that is harder to accomplish than neccessary, but not impossible. In the future it should be possible to configure what userid and groupid that Grafana runs as as to make sure that you as a user can easily control file ownership.
