### ISSUE TITLE
Can't start Grafana 5.2.1 on Kubernetes 1.10

### ISSUE THREAD

**Issue by himanshurajput32** [grafana/grafana-docker#178] opened 2018-07-19 10:45 UTC
This issue is quite similar to https://github.com/grafana/grafana-docker/issues/167.

I am trying to run Grafana 5.2.1 on Kubernetes 1.10 but the pod doesn't get started. It gives an error of permission denied when trying to write /var/lib/grafana. It works fine with grafana 5.0.0. I have also tried to put 
 ```
securityContext:
    runAsUser: 472
    fsGroup: 472
```

as advised in previous issues.
I know that there is an issue with user/group.

Finally, I found it working by using https://hub.docker.com/r/bitnami/grafana/
Can anyone please compare both Dockerfiles and provide a good solution with official grafana docker image.

**Comment by xlson** [comment] 2018-09-07 08:59
Duplicate of #167

**Closed by xlson** 2018-09-07 08:59 UTC
